[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[test]]
name = "tests"
path = "tests/byteorder-test.rs"
harness = false

[dependencies]
bevy = {version="0.8.0", features=["dynamic"]}
bevy-inspector-egui = "0.12.1"
bevy_egui = "0.16.0"
serde = "1.0.144"
serde_json = "1.0.83"
byteorder = "1"

